# SPDX-FileCopyrightText: Copyright (c) 2026 contributors to SOL ExecBench ROCm Port
# SPDX-License-Identifier: Apache-2.0

"""Current schema versions for SOLAR artifact families."""

from typing import Final

IR_GRAPH_SCHEMA_VERSION: Final = 3
SOLAR_ANALYSIS_SCHEMA_VERSION: Final = 3
OROJENESIS_IDENTITY_SCHEMA_VERSION: Final = 1
OROJENESIS_ANALYSIS_SCHEMA_VERSION: Final = 2
OROJENESIS_MULTI_EINSUM_PROBLEM_SCHEMA_VERSION: Final = 1
OROJENESIS_MULTI_EINSUM_REGION_SCHEMA_VERSION: Final = 1
SOLAR_REQUEST_MANIFEST_SCHEMA_VERSION: Final = 3
IR_VERIFICATION_SCHEMA_VERSION: Final = "solar.verification.ir.v2"
AMD_RESOURCE_MODEL_VERSION: Final = "amd_resource_v1"
RESOURCE_PEAK_CALIBRATION_SCHEMA_VERSION: Final = (
    "solar.resource_peak_calibration.v3"
)

CURRENT_NUMERIC_SCHEMA_VERSIONS: Final[dict[str, int]] = {
    "ir_graph": IR_GRAPH_SCHEMA_VERSION,
    "solar_analysis": SOLAR_ANALYSIS_SCHEMA_VERSION,
    "orojenesis_identity": OROJENESIS_IDENTITY_SCHEMA_VERSION,
    "orojenesis_analysis": OROJENESIS_ANALYSIS_SCHEMA_VERSION,
    "orojenesis_multi_einsum_problem": (
        OROJENESIS_MULTI_EINSUM_PROBLEM_SCHEMA_VERSION
    ),
    "orojenesis_multi_einsum_region": (
        OROJENESIS_MULTI_EINSUM_REGION_SCHEMA_VERSION
    ),
    "solar_request_manifest": SOLAR_REQUEST_MANIFEST_SCHEMA_VERSION,
}

CURRENT_STRING_SCHEMA_VERSIONS: Final[frozenset[str]] = frozenset(
    {
        IR_VERIFICATION_SCHEMA_VERSION,
        RESOURCE_PEAK_CALIBRATION_SCHEMA_VERSION,
    },
)

__all__ = [
    "AMD_RESOURCE_MODEL_VERSION",
    "CURRENT_NUMERIC_SCHEMA_VERSIONS",
    "CURRENT_STRING_SCHEMA_VERSIONS",
    "IR_GRAPH_SCHEMA_VERSION",
    "IR_VERIFICATION_SCHEMA_VERSION",
    "OROJENESIS_ANALYSIS_SCHEMA_VERSION",
    "OROJENESIS_IDENTITY_SCHEMA_VERSION",
    "OROJENESIS_MULTI_EINSUM_PROBLEM_SCHEMA_VERSION",
    "OROJENESIS_MULTI_EINSUM_REGION_SCHEMA_VERSION",
    "RESOURCE_PEAK_CALIBRATION_SCHEMA_VERSION",
    "SOLAR_ANALYSIS_SCHEMA_VERSION",
    "SOLAR_REQUEST_MANIFEST_SCHEMA_VERSION",
]
