# SPDX-FileCopyrightText: Copyright (c) 2026 contributors to SOL ExecBench ROCm Port
# SPDX-License-Identifier: Apache-2.0

"""AMD-native scoring support convenience exports."""

from __future__ import annotations

from importlib import import_module
from typing import Any

_EXPORTS = {
    "AUTHORITY_SLICE_SCHEMA_VERSION": ".authority_slice",
    "AuthoritySliceManifest": ".authority_slice",
    "AuthoritySliceSelectionPolicy": ".authority_slice",
    "authority_slice_manifest_from_dict": ".authority_slice",
    "build_authority_slice_manifest": ".authority_slice",
    "AMD_SOL_SCHEMA_VERSION": ".amd_sol",
    "AmdHardwareModel": ".amd_sol",
    "AmdSolBoundArtifact": ".amd_sol",
    "EstimateConfidence": ".amd_sol",
    "GraphNode": ".amd_sol",
    "HardwareValidationStatus": ".amd_sol",
    "OpSolBound": ".amd_sol",
    "WorkEstimate": ".amd_sol",
    "build_amd_sol_bound_artifact": ".amd_sol",
    "default_amd_hardware_models": ".amd_sol",
    "estimate_work": ".amd_sol",
    "extract_graph": ".amd_sol",
    "AMD_SOL_V3_SCHEMA_VERSION": ".amd_sol.v3",
    "AmdSolBoundV3Artifact": ".amd_sol.v3",
    "AmdSolAggregateBound": ".amd_sol.v3",
    "AmdSolCoverageSummary": ".amd_sol.v3",
    "AmdSolV3GroupBound": ".amd_sol.v3",
    "amd_sol_bound_v3_from_dict": ".amd_sol.v3",
    "build_amd_sol_bound_v3_artifact": ".amd_sol.v3",
    "BoundEdge": ".amd_bound_graph",
    "BoundGraph": ".amd_bound_graph",
    "BoundGraphNode": ".amd_bound_graph",
    "BoundTensor": ".amd_bound_graph",
    "BoundTensorRole": ".amd_bound_graph",
    "OpFamily": ".amd_bound_graph",
    "build_bound_graph": ".amd_bound_graph",
    "OperatorWorkEstimate": ".amd_bound_estimate.estimates",
    "estimate_bound_work": ".amd_bound_estimate.estimates",
    "AMD_HARDWARE_MODEL_SCHEMA_VERSION": ".amd_hardware_models",
    "amd_hardware_model_from_dict": ".amd_hardware_models",
    "load_amd_hardware_model": ".amd_hardware_models",
    "load_packaged_amd_hardware_model": ".amd_hardware_models",
    "AMD_SCORE_CLAIM_LEVEL": ".amd_score",
    "AMD_SCORE_SCHEMA_VERSION": ".amd_score",
    "CDNA3_NO_VALIDATION_WARNING": ".amd_score",
    "DEGRADED_SOL_BOUND_WARNING": ".amd_score",
    "INCOMPLETE_EVIDENCE_WARNING": ".amd_score",
    "REFERENCE_BASELINE_WARNING": ".amd_score",
    "UNSCORED_SOL_BOUND_WARNING": ".amd_score",
    "UNSUPPORTED_EVIDENCE_WARNING": ".amd_score",
    "UNVALIDATED_HARDWARE_WARNING": ".amd_score",
    "AmdNativeScore": ".amd_score",
    "AmdNativeSuiteReport": ".amd_score",
    "build_amd_native_suite_report": ".amd_score",
    "score_amd_native_workload": ".amd_score",
    "BASELINE_ARTIFACT_SCHEMA_VERSION": ".baseline_artifact",
    "ScoringBaselineArtifact": ".baseline_artifact",
    "ScoringBaselineEntry": ".baseline_artifact",
    "load_scoring_baseline_artifact": ".baseline_artifact",
    "scoring_baseline_artifact_from_dict": ".baseline_artifact",
    "CLASSIFICATIONS": ".release_baseline",
    "RELEASE_BASELINE_BUNDLE_SCHEMA_VERSION": ".release_baseline",
    "RELEASE_BASELINE_VERIFICATION_SCHEMA_VERSION": ".release_baseline",
    "ReleaseBaselineBundle": ".release_baseline",
    "ReleaseBaselineVerification": ".release_baseline",
    "ReleaseBaselineVerificationWorkload": ".release_baseline",
    "ReleaseBaselineWorkload": ".release_baseline",
    "ReleaseProvenance": ".release_baseline",
    "load_release_baseline_bundle": ".release_baseline",
    "release_baseline_bundle_from_dict": ".release_baseline",
    "release_baseline_verification_from_dict": ".release_baseline",
    "sha256_file": ".release_baseline",
    "write_release_baseline_bundle": ".release_baseline",
    "write_release_baseline_verification": ".release_baseline",
    "verify_release_baseline_rerun": ".release_baseline",
    "BASELINE_COVERAGE_FAILED_BLOCKER": ".official_score",
    "CandidateScoreEvidence": ".official_score",
    "MISSING_AGGREGATION_POLICY_BLOCKER": ".official_score",
    "MISSING_BASELINE_BLOCKER": ".official_score",
    "MISSING_MEASURED_LATENCY_BLOCKER": ".official_score",
    "MISSING_SCORE_BLOCKER": ".official_score",
    "MISSING_SOL_BOUND_BLOCKER": ".official_score",
    "OFFICIAL_SCORE_CLAIM_LEVEL": ".official_score",
    "OFFICIAL_SCORE_KIND": ".official_score",
    "OFFICIAL_SCORE_SCHEMA_VERSION": ".official_score",
    "OFFICIAL_SCORE_SOURCE": ".official_score",
    "PLACEHOLDER_BASELINE_BLOCKER": ".official_score",
    "OfficialScoreEvidence": ".official_score",
    "OfficialScoreSuiteEvidence": ".official_score",
    "build_official_score_suite_evidence": ".official_score",
    "official_score_from_amd_native_score": ".official_score",
}

__all__ = [
    "AUTHORITY_SLICE_SCHEMA_VERSION",
    "AuthoritySliceManifest",
    "AuthoritySliceSelectionPolicy",
    "AMD_SCORE_CLAIM_LEVEL",
    "AMD_SCORE_SCHEMA_VERSION",
    "AMD_SOL_SCHEMA_VERSION",
    "AMD_SOL_V3_SCHEMA_VERSION",
    "BASELINE_ARTIFACT_SCHEMA_VERSION",
    "CLASSIFICATIONS",
    "BASELINE_COVERAGE_FAILED_BLOCKER",
    "CandidateScoreEvidence",
    "AMD_HARDWARE_MODEL_SCHEMA_VERSION",
    "CDNA3_NO_VALIDATION_WARNING",
    "DEGRADED_SOL_BOUND_WARNING",
    "INCOMPLETE_EVIDENCE_WARNING",
    "MISSING_AGGREGATION_POLICY_BLOCKER",
    "MISSING_BASELINE_BLOCKER",
    "MISSING_MEASURED_LATENCY_BLOCKER",
    "MISSING_SCORE_BLOCKER",
    "MISSING_SOL_BOUND_BLOCKER",
    "OFFICIAL_SCORE_CLAIM_LEVEL",
    "OFFICIAL_SCORE_KIND",
    "OFFICIAL_SCORE_SCHEMA_VERSION",
    "OFFICIAL_SCORE_SOURCE",
    "PLACEHOLDER_BASELINE_BLOCKER",
    "REFERENCE_BASELINE_WARNING",
    "RELEASE_BASELINE_BUNDLE_SCHEMA_VERSION",
    "RELEASE_BASELINE_VERIFICATION_SCHEMA_VERSION",
    "UNSCORED_SOL_BOUND_WARNING",
    "UNSUPPORTED_EVIDENCE_WARNING",
    "UNVALIDATED_HARDWARE_WARNING",
    "AmdHardwareModel",
    "AmdNativeScore",
    "AmdNativeSuiteReport",
    "AmdSolBoundArtifact",
    "AmdSolBoundV3Artifact",
    "AmdSolAggregateBound",
    "AmdSolCoverageSummary",
    "AmdSolV3GroupBound",
    "BoundEdge",
    "BoundGraph",
    "BoundGraphNode",
    "BoundTensor",
    "BoundTensorRole",
    "EstimateConfidence",
    "GraphNode",
    "HardwareValidationStatus",
    "OpFamily",
    "OpSolBound",
    "OperatorWorkEstimate",
    "OfficialScoreEvidence",
    "OfficialScoreSuiteEvidence",
    "ScoringBaselineArtifact",
    "ScoringBaselineEntry",
    "ReleaseBaselineBundle",
    "ReleaseBaselineVerification",
    "ReleaseBaselineVerificationWorkload",
    "ReleaseBaselineWorkload",
    "ReleaseProvenance",
    "WorkEstimate",
    "build_bound_graph",
    "build_authority_slice_manifest",
    "authority_slice_manifest_from_dict",
    "build_amd_native_suite_report",
    "amd_hardware_model_from_dict",
    "load_amd_hardware_model",
    "load_packaged_amd_hardware_model",
    "build_amd_sol_bound_artifact",
    "build_amd_sol_bound_v3_artifact",
    "default_amd_hardware_models",
    "amd_sol_bound_v3_from_dict",
    "estimate_work",
    "estimate_bound_work",
    "extract_graph",
    "load_scoring_baseline_artifact",
    "load_release_baseline_bundle",
    "release_baseline_bundle_from_dict",
    "release_baseline_verification_from_dict",
    "scoring_baseline_artifact_from_dict",
    "build_official_score_suite_evidence",
    "official_score_from_amd_native_score",
    "score_amd_native_workload",
    "sha256_file",
    "write_release_baseline_bundle",
    "write_release_baseline_verification",
    "verify_release_baseline_rerun",
]


def __getattr__(name: str) -> Any:
    """Load package exports on first access."""
    module_name = _EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(module_name, __name__), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    """Return stable names for interactive discovery and star imports."""
    return sorted({*globals(), *__all__})
