# SPDX-FileCopyrightText: Copyright (c) 2026 contributors to SOL ExecBench ROCm Port
# SPDX-License-Identifier: Apache-2.0

"""AMD-native scoring support modules."""

from .amd_sol import (
    AMD_SOL_SCHEMA_VERSION,
    AmdHardwareModel,
    AmdSolBoundArtifact,
    EstimateConfidence,
    GraphNode,
    HardwareValidationStatus,
    OpSolBound,
    WorkEstimate,
    build_amd_sol_bound_artifact,
    default_amd_hardware_models,
    estimate_work,
    extract_graph,
)
from .amd_sol_v2 import (
    AMD_SOL_V2_SCHEMA_VERSION,
    AmdSolBoundV2Artifact,
    AmdSolV2AggregateBound,
    AmdSolV2CoverageSummary,
    AmdSolV2OpBound,
    amd_sol_bound_v2_from_dict,
    build_amd_sol_bound_v2_artifact,
)
from .amd_bound_graph import (
    BoundEdge,
    BoundGraph,
    BoundGraphNode,
    BoundTensor,
    BoundTensorRole,
    OpFamily,
    build_bound_graph,
)
from .amd_bound_estimates import (
    OperatorWorkEstimate,
    estimate_bound_work,
)
from .amd_hardware_models import (
    AMD_HARDWARE_MODEL_SCHEMA_VERSION,
    amd_hardware_model_from_dict,
    load_amd_hardware_model,
    load_packaged_amd_hardware_model,
)
from .amd_score import (
    AMD_SCORE_CLAIM_LEVEL,
    AMD_SCORE_SCHEMA_VERSION,
    CDNA3_NO_VALIDATION_WARNING,
    DEGRADED_SOL_BOUND_WARNING,
    INCOMPLETE_EVIDENCE_WARNING,
    REFERENCE_BASELINE_WARNING,
    UNSCORED_SOL_BOUND_WARNING,
    UNSUPPORTED_EVIDENCE_WARNING,
    UNVALIDATED_HARDWARE_WARNING,
    AmdNativeScore,
    AmdNativeSuiteReport,
    build_amd_native_suite_report,
    score_amd_native_workload,
)
from .baseline_artifact import (
    BASELINE_ARTIFACT_SCHEMA_VERSION,
    ScoringBaselineArtifact,
    ScoringBaselineEntry,
    load_scoring_baseline_artifact,
    scoring_baseline_artifact_from_dict,
)

__all__ = [
    "AMD_SCORE_CLAIM_LEVEL",
    "AMD_SCORE_SCHEMA_VERSION",
    "AMD_SOL_SCHEMA_VERSION",
    "AMD_SOL_V2_SCHEMA_VERSION",
    "BASELINE_ARTIFACT_SCHEMA_VERSION",
    "AMD_HARDWARE_MODEL_SCHEMA_VERSION",
    "CDNA3_NO_VALIDATION_WARNING",
    "DEGRADED_SOL_BOUND_WARNING",
    "INCOMPLETE_EVIDENCE_WARNING",
    "REFERENCE_BASELINE_WARNING",
    "UNSCORED_SOL_BOUND_WARNING",
    "UNSUPPORTED_EVIDENCE_WARNING",
    "UNVALIDATED_HARDWARE_WARNING",
    "AmdHardwareModel",
    "AmdNativeScore",
    "AmdNativeSuiteReport",
    "AmdSolBoundArtifact",
    "AmdSolBoundV2Artifact",
    "AmdSolV2AggregateBound",
    "AmdSolV2CoverageSummary",
    "AmdSolV2OpBound",
    "BoundEdge",
    "BoundGraph",
    "BoundGraphNode",
    "BoundTensor",
    "BoundTensorRole",
    "EstimateConfidence",
    "GraphNode",
    "HardwareValidationStatus",
    "OpFamily",
    "OpSolBound",
    "OperatorWorkEstimate",
    "ScoringBaselineArtifact",
    "ScoringBaselineEntry",
    "WorkEstimate",
    "build_bound_graph",
    "build_amd_native_suite_report",
    "amd_hardware_model_from_dict",
    "load_amd_hardware_model",
    "load_packaged_amd_hardware_model",
    "build_amd_sol_bound_artifact",
    "build_amd_sol_bound_v2_artifact",
    "default_amd_hardware_models",
    "amd_sol_bound_v2_from_dict",
    "estimate_work",
    "estimate_bound_work",
    "extract_graph",
    "load_scoring_baseline_artifact",
    "scoring_baseline_artifact_from_dict",
    "score_amd_native_workload",
]
