# SPDX-FileCopyrightText: Copyright (c) 2026 contributors to SOL ExecBench ROCm Port
# SPDX-License-Identifier: Apache-2.0

"""Public ROCm profiler API exports."""

from __future__ import annotations

import subprocess

from sol_execbench.core.bench.rocm_profiler.artifacts import (
    _classify_profile_artifact,
    _has_profiler_data_artifact,
    _is_known_profile_artifact_name,
    _is_profile_artifact_candidate,
    _is_profiler_data_artifact,
    _is_unprefixed_profile_artifact_name,
    _normalize_profile_artifact_token,
    _profile_artifact_coverage_metadata,
    _profile_artifact_sort_key,
    _profile_output_directory_listing,
    classify_profile_artifact,
    discover_rocprofv3_artifacts,
    has_profiler_data_artifact,
    is_profiler_data_artifact,
    profile_output_directory_listing,
)
from sol_execbench.core.bench.rocm_profiler.commands import (
    ProfileRunner,
    ProfilerRunner,
    _default_profile_runner,
    _default_runner,
    build_rocprofv3_command,
    build_rocprofv3_profile_command,
    default_profile_runner,
    default_runner,
)
from sol_execbench.core.bench.rocm_profiler.models import (
    ROCPROFV3_EVIDENCE_SCHEMA_VERSION,
    ROCPROFV3_EXECUTABLE,
    ROCPROFV3_PROFILE_SCHEMA_VERSION,
    ROCPROF_REASON_ARTIFACTS_REGISTERED,
    ROCPROF_REASON_COMMAND_FAILED,
    ROCPROF_REASON_COMMAND_TIMEOUT,
    ROCPROF_REASON_DIAGNOSTIC_LOG_REGISTERED,
    ROCPROF_REASON_NO_REGISTERED_ARTIFACTS,
    ROCPROF_REASON_PARTIAL_ARTIFACT_COVERAGE,
    ROCPROF_REASON_UNAVAILABLE,
    ROCPROF_WARNING_INCOMPLETE_ARTIFACT_COVERAGE,
    ROCPROF_WARNING_NO_PROFILER_DATA_ARTIFACTS,
    DefaultTimingSelection,
    Rocprofv3CollectionRequest,
    Rocprofv3CollectionResult,
    Rocprofv3ProfileArtifact,
    Rocprofv3ProfileRequest,
    Rocprofv3ProfileResult,
    Rocprofv3TimingEvidence,
    Rocprofv3TimingRow,
)
from sol_execbench.core.bench.rocm_profiler.profile import (
    _prepare_profile_output_directory,
    _profile_result_metadata,
    _subprocess_text,
    _tail,
    _write_rocprofv3_diagnostic_artifact,
    collect_rocprofv3_profile,
    prepare_profile_output_directory,
    profile_result_metadata,
    subprocess_text,
    write_rocprofv3_diagnostic_artifact,
)
from sol_execbench.core.bench.rocm_profiler.timing import (
    _duration_ns,
    _find_rocprofv3_csv,
    _first_numeric,
    _first_value,
    _normalize_header,
    _read_overhead_calibration,
    build_compact_timing_evidence,
    build_timing_evidence,
    collect_rocprofv3_timing,
    collect_source_timing_evidence,
    duration_ns,
    find_rocprofv3_csv,
    first_numeric,
    first_value,
    normalize_header,
    parse_rocprofv3_csv,
    read_overhead_calibration,
    select_default_timing,
    summarize_rocprofv3_csv,
)

__all__ = [
    "_classify_profile_artifact",
    "_default_profile_runner",
    "_default_runner",
    "_duration_ns",
    "_find_rocprofv3_csv",
    "_first_numeric",
    "_first_value",
    "_has_profiler_data_artifact",
    "_is_known_profile_artifact_name",
    "_is_profile_artifact_candidate",
    "_is_profiler_data_artifact",
    "_is_unprefixed_profile_artifact_name",
    "_normalize_header",
    "_normalize_profile_artifact_token",
    "_prepare_profile_output_directory",
    "_profile_artifact_coverage_metadata",
    "_profile_artifact_sort_key",
    "_profile_output_directory_listing",
    "_profile_result_metadata",
    "_read_overhead_calibration",
    "_subprocess_text",
    "_tail",
    "_write_rocprofv3_diagnostic_artifact",
    "ROCPROFV3_EVIDENCE_SCHEMA_VERSION",
    "ROCPROFV3_EXECUTABLE",
    "ROCPROFV3_PROFILE_SCHEMA_VERSION",
    "ROCPROF_REASON_ARTIFACTS_REGISTERED",
    "ROCPROF_REASON_COMMAND_FAILED",
    "ROCPROF_REASON_COMMAND_TIMEOUT",
    "ROCPROF_REASON_DIAGNOSTIC_LOG_REGISTERED",
    "ROCPROF_REASON_NO_REGISTERED_ARTIFACTS",
    "ROCPROF_REASON_PARTIAL_ARTIFACT_COVERAGE",
    "ROCPROF_REASON_UNAVAILABLE",
    "ROCPROF_WARNING_INCOMPLETE_ARTIFACT_COVERAGE",
    "ROCPROF_WARNING_NO_PROFILER_DATA_ARTIFACTS",
    "DefaultTimingSelection",
    "ProfileRunner",
    "ProfilerRunner",
    "Rocprofv3CollectionRequest",
    "Rocprofv3CollectionResult",
    "Rocprofv3ProfileArtifact",
    "Rocprofv3ProfileRequest",
    "Rocprofv3ProfileResult",
    "Rocprofv3TimingEvidence",
    "Rocprofv3TimingRow",
    "build_compact_timing_evidence",
    "build_rocprofv3_command",
    "build_rocprofv3_profile_command",
    "build_timing_evidence",
    "classify_profile_artifact",
    "collect_rocprofv3_profile",
    "collect_rocprofv3_timing",
    "collect_source_timing_evidence",
    "default_profile_runner",
    "default_runner",
    "discover_rocprofv3_artifacts",
    "duration_ns",
    "find_rocprofv3_csv",
    "first_numeric",
    "first_value",
    "has_profiler_data_artifact",
    "is_profiler_data_artifact",
    "normalize_header",
    "parse_rocprofv3_csv",
    "prepare_profile_output_directory",
    "profile_output_directory_listing",
    "profile_result_metadata",
    "read_overhead_calibration",
    "select_default_timing",
    "subprocess",
    "subprocess_text",
    "summarize_rocprofv3_csv",
    "write_rocprofv3_diagnostic_artifact",
]
