# SPDX-FileCopyrightText: Copyright (c) 2026 contributors to SOL ExecBench ROCm Port
# SPDX-License-Identifier: Apache-2.0

"""Public ROCm profiler API exports."""

from __future__ import annotations

from sol_execbench.core.bench.rocm_profiler.artifacts import (
    classify_profile_artifact,
    discover_rocprofv3_artifacts,
    profile_output_directory_listing,
)
from sol_execbench.core.bench.rocm_profiler.commands import (
    ProfilerRunner,
    ProfileRunner,
    build_rocprofv3_command,
    build_rocprofv3_profile_command,
    default_profile_runner,
    default_runner,
)
from sol_execbench.core.bench.rocm_profiler.models import (
    ROCPROF_WARNING_INCOMPLETE_ARTIFACT_COVERAGE,
    ROCPROF_WARNING_NO_PROFILER_DATA_ARTIFACTS,
    ROCPROFV3_EVIDENCE_SCHEMA_VERSION,
    ROCPROFV3_EXECUTABLE,
    ROCPROFV3_PROFILE_SCHEMA_VERSION,
    DefaultTimingSelection,
    Rocprofv3ArtifactCoverageStatus,
    Rocprofv3ArtifactKind,
    Rocprofv3CollectionRequest,
    Rocprofv3CollectionResult,
    Rocprofv3ProfileArtifact,
    Rocprofv3ProfileRequest,
    Rocprofv3ProfileResult,
    Rocprofv3ProfileStatus,
    Rocprofv3ReasonCode,
    Rocprofv3TimingEvidence,
    Rocprofv3TimingRow,
    SourceTimingRequest,
    has_profiler_data_artifact,
    is_profiler_data_artifact,
)
from sol_execbench.core.bench.rocm_profiler.profile import (
    collect_rocprofv3_profile,
    prepare_profile_output_directory,
    profile_result_metadata,
    subprocess_text,
    write_rocprofv3_diagnostic_artifact,
)
from sol_execbench.core.bench.rocm_profiler.timing import (
    build_compact_timing_evidence,
    build_timing_evidence,
    collect_rocprofv3_timing,
    collect_source_timing_evidence,
    find_rocprofv3_csv,
    parse_rocprofv3_csv,
    read_overhead_calibration,
    select_default_timing,
    summarize_rocprofv3_csv,
)

__all__ = [
    "ROCPROFV3_EVIDENCE_SCHEMA_VERSION",
    "ROCPROFV3_EXECUTABLE",
    "ROCPROFV3_PROFILE_SCHEMA_VERSION",
    "ROCPROF_WARNING_INCOMPLETE_ARTIFACT_COVERAGE",
    "ROCPROF_WARNING_NO_PROFILER_DATA_ARTIFACTS",
    "DefaultTimingSelection",
    "ProfileRunner",
    "ProfilerRunner",
    "Rocprofv3ArtifactCoverageStatus",
    "Rocprofv3ArtifactKind",
    "Rocprofv3CollectionRequest",
    "Rocprofv3CollectionResult",
    "Rocprofv3ProfileArtifact",
    "Rocprofv3ProfileRequest",
    "Rocprofv3ProfileResult",
    "Rocprofv3ProfileStatus",
    "Rocprofv3ReasonCode",
    "Rocprofv3TimingEvidence",
    "Rocprofv3TimingRow",
    "SourceTimingRequest",
    "build_compact_timing_evidence",
    "build_rocprofv3_command",
    "build_rocprofv3_profile_command",
    "build_timing_evidence",
    "classify_profile_artifact",
    "collect_rocprofv3_profile",
    "collect_rocprofv3_timing",
    "collect_source_timing_evidence",
    "default_profile_runner",
    "default_runner",
    "discover_rocprofv3_artifacts",
    "find_rocprofv3_csv",
    "has_profiler_data_artifact",
    "is_profiler_data_artifact",
    "parse_rocprofv3_csv",
    "prepare_profile_output_directory",
    "profile_output_directory_listing",
    "profile_result_metadata",
    "read_overhead_calibration",
    "select_default_timing",
    "subprocess_text",
    "summarize_rocprofv3_csv",
    "write_rocprofv3_diagnostic_artifact",
]
